In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("melb_data.csv")

In [5]:
df.head(5)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [6]:
df.tail()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [9]:
df.describe() #to analyze the statistical summary of numerical cols

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [12]:
df.duplicated().sum() #to check duplicates

np.int64(0)

In [13]:
df.isnull().sum() #to check null values

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [16]:
df.fillna(0, inplace=True)

In [17]:
df.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

Using loc [ ]

Get all properties where Rooms = 3 and show only Suburb, Rooms, Price.

Select the rows where SellerG = "Nelson" and only show Address, Price, and SellerG.

Get the details of houses where BuildingArea is missing (NaN).

Using iloc [ ]

Extract rows 10 to 20 and columns "Rooms", "Price", "Distance" using numeric indexes.

Select every 5th row up to row 50.

Display rows [5, 10, 15] and columns [0, 2, 4].

Show the first 10 rows but only the last 2 columns.

In [25]:
# Using loc [ ]

# Get all properties where Rooms = 3 and show only Suburb, Rooms, Price.
df.loc[(df['Rooms'] == 3), ['Suburb', 'Rooms', 'Price']]

# Select the rows where SellerG = "Nelson" and only show Address, Price, and SellerG.
df.loc[(df['SellerG'] == "Nelson"), ['Address', 'Price', 'SellerG']]

# Get the details of houses where BuildingArea is missing (NaN).

IndexError: .iloc requires numeric indexers, got ['Rooms' 'Price' 'Distance']

In [26]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,0.0,0.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,0.0,0.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [27]:
# Using iloc [ ]

# Extract rows 10 to 20 and columns "Rooms", "Price", "Distance" using numeric indexes.
df.iloc[10:21, [2,4,8]]

# Select every 5th row up to row 50.

# Display rows [5, 10, 15] and columns [0, 2, 4].

# Show the first 10 rows but only the last 2 columns.

    Rooms      Price  Distance
10      2   700000.0       2.5
11      3  1350000.0       2.5
12      2   750000.0       2.5
13      2  1172500.0       2.5
14      1   441000.0       2.5
15      2  1310000.0       2.5
16      3  1200000.0       2.5
17      3  1176500.0       2.5
18      3   955000.0       2.5
19      2   890000.0       2.5
20      4  1330000.0       2.5

In [ ]:
# EXCERSICE QUESTIONS

# Find all male passengers who did not survive.
# Select passengers with Age below 18
# Select passengers with Fare greater than 100.
# Find passengers who embarked at "S" or "C" (using .isin()).
# Find passengers whose Age is between 20 and 30 (using .between()).
# Select passengers who are either in 1st or 2nd class.
# Find all female passengers in 3rd class who survived.

In [28]:
#Conditional Selection
df = pd.read_csv("Titanic-Dataset.csv")

In [29]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [32]:
df.fillna(0,inplace=True)

In [33]:
df.duplicated().sum() #to check duplicates

np.int64(0)

In [35]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [36]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,23.799293,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,17.596074,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,6.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,24.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [43]:
# Select all passengers who survived.
df[df["Survived"] == 1]

# Select all female passengers in the dataset.
df[df["Sex"] == 'female']

# Find all passengers in 1st class
df[df["Pclass"] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [2]:
df = pd.read_csv("Noisy_Student_Bag_Price_Prediction_Dataset.csv")

In [3]:
df.head()

,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,Jansport,Nylon,Small,2.0,No,Yes,Backpack,Green,13.340058,143.445135
1,Under Armour,Nylon,Large,4.0,Yes,Yes,Tote,Pink,5.918030,72.086319
2,Nike,Nylon,Large,NaN,No,Yes,Messenger,Red,24.088386,29.699631
3,Nike,Nylon,Small,1.0,Yes,No,Messenger,Pink,5.000000,27.181990
4,Under Armour,Leather,Small,8.0,Yes,No,NaN,Black,11.258172,71.953236

In [6]:
df.isnull().sum()

Brand                   2625
Material                2625
Size                    2625
Compartments            2625
Laptop Compartment      2625
Waterproof              2625
Style                   2625
Color                   2625
Weight Capacity (kg)    2625
Price                   2625
dtype: int64

In [7]:
df.fillna(0, inplace=True)

In [8]:
df.isnull().sum()

Brand                   0
Material                0
Size                    0
Compartments            0
Laptop Compartment      0
Waterproof              0
Style                   0
Color                   0
Weight Capacity (kg)    0
Price                   0
dtype: int64

In [9]:
df.duplicated().sum() #to check duplicates

np.int64(2)

In [10]:
df.describe()

       Compartments  Weight Capacity (kg)         Price
count  52500.000000          52500.000000  52500.000000
mean       5.230876             16.660382     77.820789
std        3.046159              8.276855     42.143823
min        0.000000              0.000000      0.000000
25%        3.000000              9.962247     42.723081
50%        5.000000             16.868831     78.120214
75%        8.000000             23.734124    113.828888
max       10.000000             30.000000    150.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52500 entries, 0 to 52499
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Brand                 52500 non-null  object
 1   Material              52500 non-null  object
 2   Size                  52500 non-null  object
 3   Compartments          52500 non-null  float64
 4   Laptop Compartment    52500 non-null  object
 5   Waterproof            52500 non-null  object
 6   Style                 52500 non-null  object
 7   Color                 52500 non-null  object
 8   Weight Capacity (kg)  52500 non-null  float64
 9   Price                 52500 non-null  float64
dtypes: float64(3), object(7)
memory usage: 4.0+ MB

In [18]:
# find Average and maximum price per Brand type
df.groupby('Brand')['Price'].agg(['mean','max'])

# Average price per Brand and material
df.groupby(['Brand', 'Material'])['Price'].mean()

# Add a column showing price deviation from the brand average
df['Price_Deviation'] = df.groupby('Brand')['Price'].transform(lambda x: x - x.mean())
df

,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price,Price_Deviation
0,Jansport,Nylon,Small,2.0,No,Yes,Backpack,Green,13.340058,143.445135,65.593749
1,Under Armour,Nylon,Large,4.0,Yes,Yes,Tote,Pink,5.918030,72.086319,-6.134967
2,Nike,Nylon,Large,0.0,No,Yes,Messenger,Red,24.088386,29.699631,-48.066244
3,Nike,Nylon,Small,1.0,Yes,No,Messenger,Pink,5.000000,27.181990,-50.583885
4,Under Armour,Leather,Small,8.0,Yes,No,0,Black,11.258172,71.953236,-6.268050
...,...,...,...,...,...,...,...,...,...,...,...
52495,Jansport,Nylon,Medium,3.0,No,Yes,Messenger,Gray,19.774853,61.140497,-16.710889
52496,Jansport,0,Small,8.0,No,Yes,Messenger,Red,29.822417,47.140186,-30.711200
52497,Jansport,Polyester,Large,10.0,No,Yes,Messenger,Red,13.269034,56.184138,-21.667248
52498,Adidas,Canvas,Large,5.0,No,No,Messenger,Green,28.132229,112.036966,34.585909
52499,Nike,Canvas,Large,6.0,0,Yes,Tote,Black,28.414360,42.917005,-34.848869

In [19]:
df = pd.read_csv('Sales Dataset.csv')

In [20]:
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

In [21]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
Year-Month      0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Total Amount by Category here total amount is displayed by category
pd.pivot_table(df, 
               values='Amount', 
               index='Category', 
               aggfunc='sum')

                  Amount
Category
Electronics      2054456
Furniture        2038673
Office Supplies  2089510

In [29]:
# Average Profit by Sub-Category 
pd.pivot_table(df,
               values='Profit',
               index='Sub-Category',
               aggfunc='mean')

                       Profit
Sub-Category
Binders           1369.816901
Bookcases         1340.909091
Chairs            1480.626506
Electronic Games  1427.442308
Laptops           1252.954545
Markers           1588.627273
Paper             1439.644231
Pens              1139.000000
Phones            1124.821782
Printers          1539.568421
Sofas             1253.105263
Tables            1285.213115

In [30]:
# Total Quantity Sold by Category and Sub-Category    
pd.pivot_table(df,
               values='Amount',
               index='PaymentMode',
               aggfunc='mean')

                  Amount
PaymentMode
COD          5542.669903
Credit Card  4965.286822
Debit Card   5365.519231
EMI          5111.454128
UPI          4962.194444

In [5]:
orders_df = pd.read_csv("restaurant/orders.csv")

In [6]:
orders_df

,id,date,hour,member_id,restaurant_id,total_order
0,1,2020-01-01,11:00:00.0000000,25,6,0.00
1,2,2020-01-01,11:08:00.0000000,122,4,0.00
2,3,2020-01-01,11:10:00.0000000,62,16,39.00
3,4,2020-01-01,11:13:00.0000000,171,9,0.00
4,5,2020-01-01,11:13:00.0000000,152,30,153.00
...,...,...,...,...,...,...
35995,35996,2020-07-01,23:29:00.0000000,22,14,159.82
35996,35997,2020-07-01,23:33:00.0000000,44,2,92.43
35997,35998,2020-07-01,23:34:00.0000000,199,10,46.14
35998,35999,2020-07-01,23:40:00.0000000,86,3,33.51
35999,36000,2020-07-01,23:41:00.0000000,135,1,112.59

In [7]:
restaurant_df = pd.read_csv("restaurant/restaurants.csv")

In [8]:
restaurant_df

    id restaurant_name  restaurant_type_id  income_persentage  city_id
0    1    Restaurant 1                   3              0.075        3
1    2    Restaurant 2                   5              0.100        3
2    3    Restaurant 3                   2              0.075        4
3    4    Restaurant 4                   4              0.100        4
4    5    Restaurant 5                   5              0.050        2
5    6    Restaurant 6                   1              0.050        2
6    7    Restaurant 7                   1              0.100        4
7    8    Restaurant 8                   2              0.075        5
8    9    Restaurant 9                   1              0.075        4
9   10   Restaurant 10                   4              0.100        2
10  11   Restaurant 11                   5              0.075        4
11  12   Restaurant 12                   5              0.075        3
12  13   Restaurant 13                   5              0.075        3
13  14   Restaurant 14                   1              0.050        3
14  15   Restaurant 15                   1              0.100        4
15  16   Restaurant 16                   1              0.075        3
16  17   Restaurant 17                   1              0.050        2
17  18   Restaurant 18                   3              0.050        3
18  19   Restaurant 19                   2              0.100        2
19  20   Restaurant 20                   1              0.075        2
20  21   Restaurant 21                   2              0.050        1
21  22   Restaurant 22                   1              0.075        5
22  23   Restaurant 23                   1              0.100        1
23  24   Restaurant 24                   3              0.050        1
24  25   Restaurant 25                   3              0.100        4
25  26   Restaurant 26                   2              0.075        1
26  27   Restaurant 27                   5              0.100        4
27  28   Restaurant 28                   2              0.100        1
28  29   Restaurant 29                   2              0.050        5
29  30   Restaurant 30                   4              0.075        1

In [9]:
members_df = pd.read_csv("restaurant/members.csv")
members_df

,id,first_name,surname,sex,email,city_id,monthly_budget
0,1,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4,1000.0
1,2,Landon,Bishop,F,La.Bi@gmail.com,4,500.0
2,3,Jia,Delarosa,M,Jia.De@gmail.com,4,500.0
3,4,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4,600.0
4,5,Stacie,Patel,F,St.Patel@hotmail.com,3,500.0
...,...,...,...,...,...,...,...
195,196,Juan,Barlow,M,Juan.Ba@yahoo.com,4,500.0
196,197,Natalia,Daniel,F,Natalia.Da@gmail.com,4,500.0
197,198,Drew,Begum,M,Drew.Begum@gmail.com,3,800.0
198,199,Nial,Meadows,M,Nial.Me@yahoo.com,5,500.0
199,200,Diya,Myers,F,Diya.My@walla.co.il,5,600.0

In [10]:
# Concatenate members and restaurants side by side to explore their structure.
combined = pd.concat([members_df.head(), restaurant_df.head()], axis=1)
combined

,id,first_name,surname,sex,email,city_id,monthly_budget,id,restaurant_name,restaurant_type_id,income_persentage,city_id
0,1,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4,1000.0,1,Restaurant 1,3,0.075,3
1,2,Landon,Bishop,F,La.Bi@gmail.com,4,500.0,2,Restaurant 2,5,0.100,3
2,3,Jia,Delarosa,M,Jia.De@gmail.com,4,500.0,3,Restaurant 3,2,0.075,4
3,4,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4,600.0,4,Restaurant 4,4,0.100,4
4,5,Stacie,Patel,F,St.Patel@hotmail.com,3,500.0,5,Restaurant 5,5,0.050,2

In [11]:
# Merge orders with members to see who placed each order.
orders_with_members = pd.merge(orders_df, members_df, on='id', how='inner')
orders_with_members.head(10)

,id,date,hour,member_id,restaurant_id,total_order,first_name,surname,sex,email,city_id,monthly_budget
0,1,2020-01-01,11:00:00.0000000,25,6,0.00,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4,1000.0
1,2,2020-01-01,11:08:00.0000000,122,4,0.00,Landon,Bishop,F,La.Bi@gmail.com,4,500.0
2,3,2020-01-01,11:10:00.0000000,62,16,39.00,Jia,Delarosa,M,Jia.De@gmail.com,4,500.0
3,4,2020-01-01,11:13:00.0000000,171,9,0.00,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4,600.0
4,5,2020-01-01,11:13:00.0000000,152,30,153.00,Stacie,Patel,F,St.Patel@hotmail.com,3,500.0
5,6,2020-01-01,11:13:00.0000000,166,25,120.33,Fallon,Case,M,Fa.Case@walla.co.il,3,600.0
6,7,2020-01-01,11:18:00.0000000,25,21,158.86,Asia,Tang,F,Asia.Ta@hotmail.com,4,500.0
7,8,2020-01-01,11:19:00.0000000,95,1,95.96,Jadine,Holt,F,Ja.Holt@yahoo.com,5,600.0
8,9,2020-01-01,11:19:00.0000000,40,30,0.00,Maison,Watt,M,Maison.Watt@gmail.com,2,500.0
9,10,2020-01-01,11:20:00.0000000,149,19,248.11,Mahad,Ware,M,Ma.Ware@walla.co.il,5,600.0

In [12]:
# Merge orders with restaurants to see restaurant details for each order.
orders_with_restaurants = pd.merge(orders_df,restaurant_df,on='id',how='inner')
orders_with_restaurants

,id,date,hour,member_id,restaurant_id,total_order,restaurant_name,restaurant_type_id,income_persentage,city_id
0,1,2020-01-01,11:00:00.0000000,25,6,0.00,Restaurant 1,3,0.075,3
1,2,2020-01-01,11:08:00.0000000,122,4,0.00,Restaurant 2,5,0.100,3
2,3,2020-01-01,11:10:00.0000000,62,16,39.00,Restaurant 3,2,0.075,4
3,4,2020-01-01,11:13:00.0000000,171,9,0.00,Restaurant 4,4,0.100,4
4,5,2020-01-01,11:13:00.0000000,152,30,153.00,Restaurant 5,5,0.050,2
5,6,2020-01-01,11:13:00.0000000,166,25,120.33,Restaurant 6,1,0.050,2
6,7,2020-01-01,11:18:00.0000000,25,21,158.86,Restaurant 7,1,0.100,4
7,8,2020-01-01,11:19:00.0000000,95,1,95.96,Restaurant 8,2,0.075,5
8,9,2020-01-01,11:19:00.0000000,40,30,0.00,Restaurant 9,1,0.075,4
9,10,2020-01-01,11:20:00.0000000,149,19,248.11,Restaurant 10,4,0.100,2
10,11,2020-01-01,11:25:00.0000000,28,24,131.57,Restaurant 11,5,0.075,4
11,12,2020-01-01,11:29:00.0000000,121,16,0.00,Restaurant 12,5,0.075,3
12,13,2020-01-01,11:30:00.0000000,46,7,32.94,Restaurant 13,5,0.075,3
13,14,2020-01-01,11:30:00.0000000,200,17,131.63,Restaurant 14,1,0.050,3
14,15,2020-01-01,11:32:00.0000000,158,7,72.59,Restaurant 15,1,0.100,4
15,16,2020-01-01,11:33:00.0000000,39,16,194.17,Restaurant 16,1,0.075,3
16,17,2020-01-01,11:36:00.0000000,128,18,0.00,Restaurant 17,1,0.050,2
17,18,2020-01-01,11:37:00.0000000,131,18,71.16,Restaurant 18,3,0.050,3
18,19,2020-01-01,11:37:00.0000000,181,1,0.00,Restaurant 19,2,0.100,2
19,20,2020-01-01,11:38:00.0000000,127,18,97.50,Restaurant 20,1,0.075,2
20,21,2020-01-01,11:40:00.0000000,124,13,171.27,Restaurant 21,2,0.050,1
21,22,2020-01-01,11:48:00.0000000,77,8,100.08,Restaurant 22,1,0.075,5
22,23,2020-01-01,11:49:00.0000000,23,29,141.31,Restaurant 23,1,0.100,1
23,24,2020-01-01,11:51:00.0000000,137,15,0.00,Restaurant 24,3,0.050,1
24,25,2020-01-01,11:52:00.0000000,77,25,67.28,Restaurant 25,3,0.100,4
25,26,2020-01-01,11:52:00.0000000,159,18,121.24,Restaurant 26,2,0.075,1
26,27,2020-01-01,11:53:00.0000000,46,11,244.50,Restaurant 27,5,0.100,4
27,28,2020-01-01,11:56:00.0000000,49,28,33.92,Restaurant 28,2,0.100,1
28,29,2020-01-01,11:59:00.0000000,29,15,92.25,Restaurant 29,2,0.050,5
29,30,2020-01-01,11:59:00.0000000,169,29,0.00,Restaurant 30,4,0.075,1

In [14]:
# Merge all three: orders, members, and restaurants to get a full dataset.
orders_full_dataset = pd.merge(orders_df, members_df, on='id', how='inner')
orders_full_dataset = pd.merge(orders_full_dataset, restaurant_df, on='id', how='left')
orders_full_dataset.head(11)

,id,date,hour,member_id,restaurant_id,total_order,first_name,surname,sex,email,city_id_x,monthly_budget,restaurant_name,restaurant_type_id,income_persentage,city_id_y
0,1,2020-01-01,11:00:00.0000000,25,6,0.00,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4,1000.0,Restaurant 1,3.0,0.075,3.0
1,2,2020-01-01,11:08:00.0000000,122,4,0.00,Landon,Bishop,F,La.Bi@gmail.com,4,500.0,Restaurant 2,5.0,0.100,3.0
2,3,2020-01-01,11:10:00.0000000,62,16,39.00,Jia,Delarosa,M,Jia.De@gmail.com,4,500.0,Restaurant 3,2.0,0.075,4.0
3,4,2020-01-01,11:13:00.0000000,171,9,0.00,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4,600.0,Restaurant 4,4.0,0.100,4.0
4,5,2020-01-01,11:13:00.0000000,152,30,153.00,Stacie,Patel,F,St.Patel@hotmail.com,3,500.0,Restaurant 5,5.0,0.050,2.0
5,6,2020-01-01,11:13:00.0000000,166,25,120.33,Fallon,Case,M,Fa.Case@walla.co.il,3,600.0,Restaurant 6,1.0,0.050,2.0
6,7,2020-01-01,11:18:00.0000000,25,21,158.86,Asia,Tang,F,Asia.Ta@hotmail.com,4,500.0,Restaurant 7,1.0,0.100,4.0
7,8,2020-01-01,11:19:00.0000000,95,1,95.96,Jadine,Holt,F,Ja.Holt@yahoo.com,5,600.0,Restaurant 8,2.0,0.075,5.0
8,9,2020-01-01,11:19:00.0000000,40,30,0.00,Maison,Watt,M,Maison.Watt@gmail.com,2,500.0,Restaurant 9,1.0,0.075,4.0
9,10,2020-01-01,11:20:00.0000000,149,19,248.11,Mahad,Ware,M,Ma.Ware@walla.co.il,5,600.0,Restaurant 10,4.0,0.100,2.0
10,11,2020-01-01,11:25:00.0000000,28,24,131.57,Louisa,Grant,F,Lo.Gr@gmail.com,2,600.0,Restaurant 11,5.0,0.075,4.0

In [15]:
# Join orders with restaurants using the index.
members_df.reset_index(inplace=True)
members_df.set_index('id', inplace=True)
orders_with_members = orders_df.join(members_df, on='id', how='left')
orders_with_members.head()

,id,date,hour,member_id,restaurant_id,total_order,index,first_name,surname,sex,email,city_id,monthly_budget
0,1,2020-01-01,11:00:00.0000000,25,6,0.0,0.0,Ollie,Kinney,M,Ol.Kinney@walla.co.il,4.0,1000.0
1,2,2020-01-01,11:08:00.0000000,122,4,0.0,1.0,Landon,Bishop,F,La.Bi@gmail.com,4.0,500.0
2,3,2020-01-01,11:10:00.0000000,62,16,39.0,2.0,Jia,Delarosa,M,Jia.De@gmail.com,4.0,500.0
3,4,2020-01-01,11:13:00.0000000,171,9,0.0,3.0,Valentina,Ratcliffe,F,Va.Ratcliffe@gmail.com,4.0,600.0
4,5,2020-01-01,11:13:00.0000000,152,30,153.0,4.0,Stacie,Patel,F,St.Patel@hotmail.com,3.0,500.0

In [17]:
# Join orders with members using the index.
popular_restaurants = orders_full_dataset.groupby('restaurant_name')['id'].count().reset_index()
popular_restaurants = popular_restaurants.sort_values(by='id', ascending=False)
popular_restaurants.head()

  restaurant_name  id
0    Restaurant 1   1
1   Restaurant 10   1
2   Restaurant 11   1
3   Restaurant 12   1
4   Restaurant 13   1